In [ ]:
# The following notebook demonstrates some of the integral methods of preprocessing data for your machine learning algorithm

In [4]:
# Problem 1: OneHotEncoder Basics
# Prompt: You have a dataset containing a single categorical column 'Fruit' with following values:
# '['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry', 'Banana']
# Write a script to use 'OneHotEncoder' to transform this column into a binary matrix

import pandas as pd
data = ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry', 'Banana']
df = pd.DataFrame(data, columns=['Fruit'])
from sklearn.preprocessing import OneHotEncoder

# Using OneHotEncoder
df = pd.get_dummies(df, columns=['Fruit'],drop_first=0)
df

   Fruit_Apple  Fruit_Banana  Fruit_Cherry
0         True         False         False
1        False          True         False
2        False         False          True
3         True         False         False
4        False         False          True
5        False          True         False

In [10]:
# Problem 2: StandardScaler Basics
# Prompt: You have a dataset containing a single numeric column 'Height' with the following values:
# '[150, 160, 170, 180, 190, 200]'
# Write a script to use 'StandardScaler' to standardize this column

import pandas as pd
data = [150, 160, 170, 180, 190, 200]
df = pd.DataFrame(data, columns=['Height'])
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
standard_scaler.fit_transform(df)

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

In [26]:
# Problem 3: Combining OneHotEncoder and StandardScaler
# Prompt: You have a dataset with two columns: 'Age' and 'City'
# The 'Age' column contains numeric values '[23,45,31,35,27]'
# The 'City' column contains categorical values:
# '['New York', 'Los Angelas', 'Chicago', 'New York', 'Chicago']'
# Write a script to apply 'StandardScaler' to the appropriate columns

import pandas as pd
data = {'Age': [23,45,31,35,27],'City': ['New York', 'Los Angelas', 'Chicago', 'New York', 'Chicago']}
df = pd.DataFrame(data, columns=['Age','City'])

# StandardScaler
scaler = StandardScaler()
df['Age'] = scaler.fit_transform(df[['Age']])

# OneHotEncoder
df = pd.get_dummies(df, columns=['City'])
df

        Age  City_Chicago  City_Los Angelas  City_New York
0 -1.218998         False             False           True
1  1.695997         False              True          False
2 -0.159000          True             False          False
3  0.370999         False             False           True
4 -0.688999          True             False          False

In [34]:
# Problem 4: Using a Pipeline
# Prompt: Create a pipeline that first preprocesses the respective data:
# The 'Salary' column contains '[50000, 60000, 75000, 80000]'
# The 'Department' column contains '['HR', 'Engineering', 'Sales', 'Engineering']'

import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Create the DataFrame
data = {
    'Salary': [50000, 60000, 75000, 80000],
    'Department': ['HR', 'Engineering', 'Sales', 'Engineering']
}
df = pd.DataFrame(data)

# Define the ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Salary']),
        ('cat', OneHotEncoder(), ['Department'])
    ]
)

# Create the pipeline
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit and transform the data
preprocessed_data = pipeline.fit_transform(df)

# Convert the result back to a DataFrame for better readability
preprocessed_df = pd.DataFrame(preprocessed_data, columns=['Salary_scaled', 'Department_Engineering', 'Department_HR', 'Department_Sales'])
preprocessed_df

   Salary_scaled  Department_Engineering  Department_HR  Department_Sales
0      -1.362770                     0.0            1.0               0.0
1      -0.524142                     1.0            0.0               0.0
2       0.733799                     0.0            0.0               1.0
3       1.153113                     1.0            0.0               0.0

In [28]:
# Problem 5: Custom Dataset
# Prompt: Problem: You have a dataset with three columns: Weight, Gender, and Country. 
# The Weight column contains [60, 70, 80, 90, 100], 
# The Gender column contains ['Male', 'Female', 'Female', 'Male', 'Male'],
# and the Country column contains ['USA', 'Canada', 'USA', 'Canada', 'USA']. 
#Write a script to create a pipeline that scales the Weight column and applies one-hot encoding to both the Gender and Country columns.

import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

data = {
    'Weight': [60, 70, 80, 90, 100],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Male'],
    'Country': ['USA', 'Canada', 'USA', 'Canada', 'USA']
}
df = pd.DataFrame(data, columns=['Weight','Gender','Country'])

preprocessor = ColumnTransformer(
    transformers= [
        ('num', StandardScaler(),['Weight']),
        ('cat',OneHotEncoder(),['Gender','Country'])
    ]
)

pipeline = Pipeline(steps=[('preprocessor',preprocessor)])

preprocessed_data = pipeline.fit_transform(df)

# preprocessed_frame = pd.DataFrame(preprocessed_data)
# preprocessed_frame

# Get feature names
# Extract column names for the OneHotEncoded part
one_hot_columns = preprocessor.named_transformers_['cat'].get_feature_names_out(['Gender', 'Country'])
# Combine with the numeric column
column_names = ['Weight_scaled'] + one_hot_columns.tolist()

# Create the DataFrame with the correct column names
preprocessed_frame = pd.DataFrame(preprocessed_data, columns=column_names)
print(preprocessed_frame)

   Weight_scaled  Gender_Female  Gender_Male  Country_Canada  Country_USA
0      -1.414214            0.0          1.0             0.0          1.0
1      -0.707107            1.0          0.0             1.0          0.0
2       0.000000            1.0          0.0             0.0          1.0
3       0.707107            0.0          1.0             1.0          0.0
4       1.414214            0.0          1.0             0.0          1.0

In [4]:
# Problem 6: Combining OneHotEncoder and Standard Scaler
# Prompt: Create a pipeline that first standardizes the numeric column Price and then applies one-hot encoding to the categorical column Product. 
# The Price column contains [10, 20, 15, 25],
# Product column contains ['A', 'B', 'A', 'C']. 
# Write a script to achieve this

import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

data = {
    'Price': [10,20,15,25],
    'Product': ['A','B','A','C']
}

df = pd.DataFrame(data,columns=['Price','Product'])

preprocessor = ColumnTransformer(
    transformers = [
        ('num', StandardScaler(),['Price']),
        ('cat',OneHotEncoder(),['Product'])
    ]
)

pipeline = Pipeline(steps=[('preprocessor',preprocessor)])

preprocessor_data = pipeline.fit_transform(df)

one_hot_columns = preprocessor.named_transformers_['cat'].get_feature_names_out(['Product'])
column_names = ['Prices_scaled'] + one_hot_columns.tolist()

preprocessor_df = pd.DataFrame(preprocessor_data, columns = column_names)
preprocessor_df

   Prices_scaled  Product_A  Product_B  Product_C
0      -1.341641        1.0        0.0        0.0
1       0.447214        0.0        1.0        0.0
2      -0.447214        1.0        0.0        0.0
3       1.341641        0.0        0.0        1.0

In [23]:
# Problem 7: Pipeline with Mixed Data Types
# Prompt: You have a dataset with three columns: Age, City, and Income.
# The Age column contains [25, 30, 35, 40]
# City column contains ['New York', 'Chicago', 'San Francisco', 'New York']
# Income column contains [50000, 60000, 70000, 80000].
# Create a pipeline that scales the Age and Income columns and applies one-hot encoding to the City column

import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Creating the initial DataFrame
data = {
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Chicago', 'San Francisco', 'New York'],
    'Income': [50000, 60000, 70000, 80000]
}

df = pd.DataFrame(data, columns=['Age', 'City', 'Income'])

# Preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Age', 'Income']),
        ('cat', OneHotEncoder(), ['City'])
    ]
)

pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Fit the pipeline
pipeline.fit(df)

# Get the feature names
one_hot_columns = pipeline.named_steps['preprocessor'].named_transformers_['cat'].get_feature_names_out(['City'])
# Combine with the numeric columns
column_names = ['Age_scaled', 'Income_scaled'] + one_hot_columns.tolist()

# Transform the data
preprocessed_data = pipeline.transform(df)

# Create a new DataFrame using the preprocessed data
preprocessed_frame = pd.DataFrame(preprocessed_data, columns=column_names)
print(preprocessed_frame)

   Age_scaled  Income_scaled  City_Chicago  City_New York  City_San Francisco
0   -1.341641      -1.341641           0.0            1.0                 0.0
1   -0.447214      -0.447214           1.0            0.0                 0.0
2    0.447214       0.447214           0.0            0.0                 1.0
3    1.341641       1.341641           0.0            1.0                 0.0